package com.qf.group6.dao;

import com.qf.group6.entity.CatGoods;

public interface CatGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(CatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(CatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    CatGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(CatGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(CatGoods record);
}