package com.qf.group6.dao;

import com.qf.group6.entity.DynUserComment;

public interface DynUserCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(DynUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(DynUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    DynUserComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(DynUserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(DynUserComment record);
}