package com.qf.group6.dao;

import com.qf.group6.entity.DynUserLike;

public interface DynUserLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(DynUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(DynUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    DynUserLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(DynUserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(DynUserLike record);
}