package com.qf.group6.dao;

import com.qf.group6.entity.PetInfo;

public interface PetInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(PetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(PetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    PetInfo selectByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(PetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(PetInfo record);
}