package com.qf.group6.dao;

import com.qf.group6.entity.TopicUser;

public interface TopicUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(TopicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(TopicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    TopicUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(TopicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(TopicUser record);

    /**
     * 通过用户ID查看相关信息
     * @param userId 用户ID
     * @return R对象
     */
    TopicUser findByUserId(Integer userId);


}