package com.qf.group6.dao;

import com.qf.group6.entity.TopicInfo;

import java.util.List;

public interface TopicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(TopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(TopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    TopicInfo selectByPrimaryKey(Integer topicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(TopicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(TopicInfo record);

    /**
     * 通过用户id查看话题详情
     * @param userId
     * @return
     */
    List<TopicInfo> findTopicInfoByUserId(Integer userId);

    List<TopicInfo> findAll();

    /**
     * 通过话题id查询评论列表
     * @param topicId 话题id
     * @return List集合
     */
    List<TopicInfo> findComment(Integer topicId);

    /**
     * 个人列表模块
     * @param userId 用户id
     * @return
     */
    List<TopicInfo> findByUserId (Integer userId);

}