package com.qf.group6.dao;

import com.qf.group6.entity.UserFocusUser;

import java.util.List;

public interface UserFocusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insert(UserFocusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int insertSelective(UserFocusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    UserFocusUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKeySelective(UserFocusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_focus_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    int updateByPrimaryKey(UserFocusUser record);


    /**
     * 通过用户Id查看被关注人的id
     * @param userId
     * @return
     */
    List<UserFocusUser> findByUserId(Integer userId);

}