package com.qf.group6.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class CatGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_goods.cat_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_goods.cat_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private BigDecimal catPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_goods.cat_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String catPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat_goods.cat_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String catInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cat_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_goods.id
     *
     * @return the value of cat_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_goods.id
     *
     * @param id the value for cat_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_goods.cat_name
     *
     * @return the value of cat_goods.cat_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_goods.cat_name
     *
     * @param catName the value for cat_goods.cat_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_goods.cat_price
     *
     * @return the value of cat_goods.cat_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public BigDecimal getCatPrice() {
        return catPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_goods.cat_price
     *
     * @param catPrice the value for cat_goods.cat_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setCatPrice(BigDecimal catPrice) {
        this.catPrice = catPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_goods.cat_photo
     *
     * @return the value of cat_goods.cat_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getCatPhoto() {
        return catPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_goods.cat_photo
     *
     * @param catPhoto the value for cat_goods.cat_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setCatPhoto(String catPhoto) {
        this.catPhoto = catPhoto == null ? null : catPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat_goods.cat_info
     *
     * @return the value of cat_goods.cat_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getCatInfo() {
        return catInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat_goods.cat_info
     *
     * @param catInfo the value for cat_goods.cat_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setCatInfo(String catInfo) {
        this.catInfo = catInfo == null ? null : catInfo.trim();
    }
}