package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class DynInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_ content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date dynDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_video
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_cover
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_title
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_abstract
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.dyn_body
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyn_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.id
     *
     * @return the value of dyn_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.id
     *
     * @param id the value for dyn_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_ content
     *
     * @return the value of dyn_info.dyn_ content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynContent() {
        return dynContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_ content
     *
     * @param dynContent the value for dyn_info.dyn_ content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynContent(String dynContent) {
        this.dynContent = dynContent == null ? null : dynContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_date
     *
     * @return the value of dyn_info.dyn_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getDynDate() {
        return dynDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_date
     *
     * @param dynDate the value for dyn_info.dyn_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynDate(Date dynDate) {
        this.dynDate = dynDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_photo
     *
     * @return the value of dyn_info.dyn_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynPhoto() {
        return dynPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_photo
     *
     * @param dynPhoto the value for dyn_info.dyn_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynPhoto(String dynPhoto) {
        this.dynPhoto = dynPhoto == null ? null : dynPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_video
     *
     * @return the value of dyn_info.dyn_video
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynVideo() {
        return dynVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_video
     *
     * @param dynVideo the value for dyn_info.dyn_video
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynVideo(String dynVideo) {
        this.dynVideo = dynVideo == null ? null : dynVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_cover
     *
     * @return the value of dyn_info.dyn_cover
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynCover() {
        return dynCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_cover
     *
     * @param dynCover the value for dyn_info.dyn_cover
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynCover(String dynCover) {
        this.dynCover = dynCover == null ? null : dynCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_title
     *
     * @return the value of dyn_info.dyn_title
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynTitle() {
        return dynTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_title
     *
     * @param dynTitle the value for dyn_info.dyn_title
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynTitle(String dynTitle) {
        this.dynTitle = dynTitle == null ? null : dynTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_abstract
     *
     * @return the value of dyn_info.dyn_abstract
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynAbstract() {
        return dynAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_abstract
     *
     * @param dynAbstract the value for dyn_info.dyn_abstract
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynAbstract(String dynAbstract) {
        this.dynAbstract = dynAbstract == null ? null : dynAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.dyn_body
     *
     * @return the value of dyn_info.dyn_body
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynBody() {
        return dynBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.dyn_body
     *
     * @param dynBody the value for dyn_info.dyn_body
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynBody(String dynBody) {
        this.dynBody = dynBody == null ? null : dynBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_info.user_id
     *
     * @return the value of dyn_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_info.user_id
     *
     * @param userId the value for dyn_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}