package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class DynUserComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_comment.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_comment.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer dynId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_comment.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_comment.dyn_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String dynComContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_comment.dyn_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date dynComDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyn_user_comment
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_comment.id
     *
     * @return the value of dyn_user_comment.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_comment.id
     *
     * @param id the value for dyn_user_comment.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_comment.dyn_id
     *
     * @return the value of dyn_user_comment.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getDynId() {
        return dynId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_comment.dyn_id
     *
     * @param dynId the value for dyn_user_comment.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynId(Integer dynId) {
        this.dynId = dynId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_comment.user_id
     *
     * @return the value of dyn_user_comment.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_comment.user_id
     *
     * @param userId the value for dyn_user_comment.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_comment.dyn_com_content
     *
     * @return the value of dyn_user_comment.dyn_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getDynComContent() {
        return dynComContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_comment.dyn_com_content
     *
     * @param dynComContent the value for dyn_user_comment.dyn_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynComContent(String dynComContent) {
        this.dynComContent = dynComContent == null ? null : dynComContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_comment.dyn_com_date
     *
     * @return the value of dyn_user_comment.dyn_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getDynComDate() {
        return dynComDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_comment.dyn_com_date
     *
     * @param dynComDate the value for dyn_user_comment.dyn_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynComDate(Date dynComDate) {
        this.dynComDate = dynComDate;
    }
}