package com.qf.group6.entity;

import java.io.Serializable;

public class DynUserLike implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_like.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_like.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer dynId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_user_like.like_user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer likeUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dyn_user_like
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_like.id
     *
     * @return the value of dyn_user_like.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_like.id
     *
     * @param id the value for dyn_user_like.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_like.dyn_id
     *
     * @return the value of dyn_user_like.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getDynId() {
        return dynId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_like.dyn_id
     *
     * @param dynId the value for dyn_user_like.dyn_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setDynId(Integer dynId) {
        this.dynId = dynId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_user_like.like_user_id
     *
     * @return the value of dyn_user_like.like_user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getLikeUserId() {
        return likeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_user_like.like_user_id
     *
     * @param likeUserId the value for dyn_user_like.like_user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setLikeUserId(Integer likeUserId) {
        this.likeUserId = likeUserId;
    }
}