package com.qf.group6.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class GoodsCart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_cart.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_cart.goods_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_cart.goods_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_cart.goods_count
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_cart.goods_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String goodsPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_cart
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_cart.id
     *
     * @return the value of goods_cart.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_cart.id
     *
     * @param id the value for goods_cart.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_cart.goods_name
     *
     * @return the value of goods_cart.goods_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_cart.goods_name
     *
     * @param goodsName the value for goods_cart.goods_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_cart.goods_price
     *
     * @return the value of goods_cart.goods_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_cart.goods_price
     *
     * @param goodsPrice the value for goods_cart.goods_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_cart.goods_count
     *
     * @return the value of goods_cart.goods_count
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_cart.goods_count
     *
     * @param goodsCount the value for goods_cart.goods_count
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_cart.goods_photo
     *
     * @return the value of goods_cart.goods_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getGoodsPhoto() {
        return goodsPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_cart.goods_photo
     *
     * @param goodsPhoto the value for goods_cart.goods_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setGoodsPhoto(String goodsPhoto) {
        this.goodsPhoto = goodsPhoto == null ? null : goodsPhoto.trim();
    }
}