package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class HisSearch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_search.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_search.his_search_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String hisSearchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_search.his_search_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date hisSearchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column his_search.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table his_search
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_search.id
     *
     * @return the value of his_search.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_search.id
     *
     * @param id the value for his_search.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_search.his_search_name
     *
     * @return the value of his_search.his_search_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getHisSearchName() {
        return hisSearchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_search.his_search_name
     *
     * @param hisSearchName the value for his_search.his_search_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setHisSearchName(String hisSearchName) {
        this.hisSearchName = hisSearchName == null ? null : hisSearchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_search.his_search_date
     *
     * @return the value of his_search.his_search_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getHisSearchDate() {
        return hisSearchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_search.his_search_date
     *
     * @param hisSearchDate the value for his_search.his_search_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setHisSearchDate(Date hisSearchDate) {
        this.hisSearchDate = hisSearchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column his_search.user_id
     *
     * @return the value of his_search.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column his_search.user_id
     *
     * @param userId the value for his_search.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}