package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.receive_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.receive_phone
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String receivePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.receive_address
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_state
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.receive_name
     *
     * @return the value of order_info.receive_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.receive_name
     *
     * @param receiveName the value for order_info.receive_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.receive_phone
     *
     * @return the value of order_info.receive_phone
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.receive_phone
     *
     * @param receivePhone the value for order_info.receive_phone
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone == null ? null : receivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.receive_address
     *
     * @return the value of order_info.receive_address
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.receive_address
     *
     * @param receiveAddress the value for order_info.receive_address
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_date
     *
     * @return the value of order_info.order_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_date
     *
     * @param orderDate the value for order_info.order_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_state
     *
     * @return the value of order_info.order_state
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_state
     *
     * @param orderState the value for order_info.order_state
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }
}