package com.qf.group6.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class PetFoodGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String foodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String foodPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer foodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_orig_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private BigDecimal foodOrigPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_new_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private BigDecimal foodNewPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_food_goods.food_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String foodInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pet_food_goods
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.id
     *
     * @return the value of pet_food_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.id
     *
     * @param id the value for pet_food_goods.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_name
     *
     * @return the value of pet_food_goods.food_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_name
     *
     * @param foodName the value for pet_food_goods.food_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_photo
     *
     * @return the value of pet_food_goods.food_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getFoodPhoto() {
        return foodPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_photo
     *
     * @param foodPhoto the value for pet_food_goods.food_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodPhoto(String foodPhoto) {
        this.foodPhoto = foodPhoto == null ? null : foodPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_num
     *
     * @return the value of pet_food_goods.food_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getFoodNum() {
        return foodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_num
     *
     * @param foodNum the value for pet_food_goods.food_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodNum(Integer foodNum) {
        this.foodNum = foodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_orig_price
     *
     * @return the value of pet_food_goods.food_orig_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public BigDecimal getFoodOrigPrice() {
        return foodOrigPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_orig_price
     *
     * @param foodOrigPrice the value for pet_food_goods.food_orig_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodOrigPrice(BigDecimal foodOrigPrice) {
        this.foodOrigPrice = foodOrigPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_new_price
     *
     * @return the value of pet_food_goods.food_new_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public BigDecimal getFoodNewPrice() {
        return foodNewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_new_price
     *
     * @param foodNewPrice the value for pet_food_goods.food_new_price
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodNewPrice(BigDecimal foodNewPrice) {
        this.foodNewPrice = foodNewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_food_goods.food_info
     *
     * @return the value of pet_food_goods.food_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getFoodInfo() {
        return foodInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_food_goods.food_info
     *
     * @param foodInfo the value for pet_food_goods.food_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setFoodInfo(String foodInfo) {
        this.foodInfo = foodInfo == null ? null : foodInfo.trim();
    }
}