package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class TopicUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user.topic_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String topicComContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_user.topic_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date topicComDate;

    private UserInfo userInfo;


    public UserInfo getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_user
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user.id
     *
     * @return the value of topic_user.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user.id
     *
     * @param id the value for topic_user.id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user.topic_id
     *
     * @return the value of topic_user.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user.topic_id
     *
     * @param topicId the value for topic_user.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user.user_id
     *
     * @return the value of topic_user.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user.user_id
     *
     * @param userId the value for topic_user.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user.topic_com_content
     *
     * @return the value of topic_user.topic_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getTopicComContent() {
        return topicComContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user.topic_com_content
     *
     * @param topicComContent the value for topic_user.topic_com_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicComContent(String topicComContent) {
        this.topicComContent = topicComContent == null ? null : topicComContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_user.topic_com_date
     *
     * @return the value of topic_user.topic_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getTopicComDate() {
        return topicComDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_user.topic_com_date
     *
     * @param topicComDate the value for topic_user.topic_com_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicComDate(Date topicComDate) {
        this.topicComDate = topicComDate;
    }
}