package com.qf.group6.entity;

import java.io.Serializable;
import java.util.Date;

public class TopicInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String topicContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private String topicPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Date topicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.topic_com_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer topicComNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private Integer userId;

    private UserInfo userInfo;
    private TopicUser topicUser;

    public TopicUser getTopicUser() {
        return topicUser;
    }

    public void setTopicUser(TopicUser topicUser) {
        this.topicUser = topicUser;
    }

    public UserInfo getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic_info
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_id
     *
     * @return the value of topic_info.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_id
     *
     * @param topicId the value for topic_info.topic_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_name
     *
     * @return the value of topic_info.topic_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_name
     *
     * @param topicName the value for topic_info.topic_name
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_content
     *
     * @return the value of topic_info.topic_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getTopicContent() {
        return topicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_content
     *
     * @param topicContent the value for topic_info.topic_content
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicContent(String topicContent) {
        this.topicContent = topicContent == null ? null : topicContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_photo
     *
     * @return the value of topic_info.topic_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public String getTopicPhoto() {
        return topicPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_photo
     *
     * @param topicPhoto the value for topic_info.topic_photo
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicPhoto(String topicPhoto) {
        this.topicPhoto = topicPhoto == null ? null : topicPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_date
     *
     * @return the value of topic_info.topic_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Date getTopicDate() {
        return topicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_date
     *
     * @param topicDate the value for topic_info.topic_date
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicDate(Date topicDate) {
        this.topicDate = topicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.topic_com_num
     *
     * @return the value of topic_info.topic_com_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getTopicComNum() {
        return topicComNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.topic_com_num
     *
     * @param topicComNum the value for topic_info.topic_com_num
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setTopicComNum(Integer topicComNum) {
        this.topicComNum = topicComNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_info.user_id
     *
     * @return the value of topic_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_info.user_id
     *
     * @param userId the value for topic_info.user_id
     *
     * @mbggenerated Thu Jan 24 11:51:34 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}